### PR TITLE
Fix: Agent image position and aspect

### PR DESCRIPTION
**Pull request by bstien**
# Why?
We got a request to reposition the images used for the realtors in both sold state and extended profile. Currently we're using `imageView.contentMode = .scaleAspectFill`. This works in most cases and it'll fill the image in the container, but the image will be cropped to the center. In several cases the agencies provide images in vertical rectangles which can crop the head of the person.

There's no option in `UIView.ContentMode` to specify both `.scaleAspectFill` and `.top`, so AFAIK we have to redraw the image.

# What?
- Add `ContactPersonImageView`
  - Works as a proxy for it's subview `RemoteImageView`.
- Add an extension for `UIImage` that redraws the image from the top to fill its container.
- Use this view for both extended profile and sold state.

# Version Change
Patch. No API changes.

# UI Changes
The images used in the screenshots below are at the bottom.

| Before | After |
| --- | --- |
| Screenshot 2022-06-28 at 11 04 23 | Screenshot 2022-06-28 at 11 05 59 |
| Screenshot 2022-06-28 at 11 09 53 | Screenshot 2022-06-28 at 11 10 46 |

## Images used in screenshots
| Tall image | Wide image |
| --- | --- |
|  |  |

### CODE REVIEW

**Review by MarenZR — APPROVED** [review]
This looks good 👍 Now I know how to redraw an image :)

**Comment by osanoj** [comment]
> There's no option in `UIView.ContentMode` to specify both `.scaleAspectFill` and `.top`, so AFAIK we have to redraw the image.

Maybe another approach would be to check if height > width, and extend the image view outside the parent bounds (with as much as needed in regards to the width and aspect ratio) so that we only see the top of the scaleAspectFill image. I think 🤔

**Comment by bstien** [comment]
> > There's no option in `UIView.ContentMode` to specify both `.scaleAspectFill` and `.top`, so AFAIK we have to redraw the image.
> 
> Maybe another approach would be to check if height > width, and extend the image view outside the parent bounds (with as much as needed in regards to the width and aspect ratio) so that we only see the top of the scaleAspectFill image. I think 🤔

It's been some time since I did this, but I tried a similar approach IIRC. In those cases the image would then have either the wrong size or not be top and centered, depending on which dimension was bigger.

The only solution I found was to redraw the image manually to make it fit those specifications.

**Comment by osanoj** [comment]
So you already tried that approach 👍 😄 

Might be it should be in combination with scaleAspectFit instead 🤔 But this is a bit to abstract to think about without practical testing, so go ahead and merge the solution that actually works 😅

**Pull request merged**
