### PR TITLE
Remove old image

### PR DESCRIPTION
**Pull request by ag12**
# Why?
This image is deprecated and replaced with a new one. 

# What?
Update Finniverskit and Warp
Remove duplicate ad image `noImage` and use FinniversKit placeholder ad image

# Version Change
Minor

# UI Changes
Screenshot 2024-02-26 at 14 52 09

Screenshot 2024-02-26 at 14 57 39

### CODE REVIEW

**Review by BjornRuud — APPROVED** [review]

**Comment by ag12** [comment]
how does theses work?

**Comment by BjornRuud** [comment]
> how does theses work?

How does what work? 🤔

**Comment by ag12** [comment]
> > how does theses work?
> 
> How does what work? 🤔

Right 😃

**Comment by ag12** [comment]
Tests ..

**Pull request merged**
